export const DragTypes = {
    TOOL_HEADING: 'TOOL_HEADING',
    TOOL_PARAGRAPH: 'TOOL_PARAGRAPH',
    TOOL_TABLE: 'TOOL_TABLE',
    TOOL: 'TOOL'
}


export const SheetHeight = {
    SHEET_MAX_HEIGHT: 1122 - 100,
    SHEET_HEIGHT_HEADING: 65,
    SHEET_HEIGHT_PARAGRAPH: 82,
    SHEET_HEIGHT_TABLE: 160,
    SHEET_HEIGHT_TABLE_ROW: 65,
}